defmodule TalibEx.FunctionDef do
  @moduledoc false
  # Generated by tools/generate_function_def.exs — do not edit manually.

  def mapping do
    [
      %{
        name: "accbands",
        doc: "Acceleration Bands",
        target: "TA_ACCBANDS",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 20,
            doc: "Number of period"
          }
        ],
        outputs: [
          %{name: :real_upper_band, type: :double_array},
          %{name: :real_middle_band, type: :double_array},
          %{name: :real_lower_band, type: :double_array}
        ]
      },
      %{
        name: "acos",
        doc: "Vector Trigonometric ACos",
        target: "TA_ACOS",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ad",
        doc: "Chaikin A/D Line",
        target: "TA_AD",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{name: :volume, type: :double_array, doc: "Volume List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "add",
        doc: "Vector Arithmetic Add",
        target: "TA_ADD",
        inputs: [%{name: :values0, type: :double_array}, %{name: :values1, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "adosc",
        doc: "Chaikin A/D Oscillator",
        target: "TA_ADOSC",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{name: :volume, type: :double_array, doc: "Volume List"},
          %{
            name: :fast_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 3,
            doc: "Number of period for the fast MA"
          },
          %{
            name: :slow_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 10,
            doc: "Number of period for the slow MA"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "adx",
        doc: "Average Directional Movement Index",
        target: "TA_ADX",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "adxr",
        doc: "Average Directional Movement Index Rating",
        target: "TA_ADXR",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "apo",
        doc: "Absolute Price Oscillator",
        target: "TA_APO",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :fast_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 12,
            doc: "Number of period for the fast MA"
          },
          %{
            name: :slow_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 26,
            doc: "Number of period for the slow MA"
          },
          %{name: :ma_type, type: :ma_type, default: :sma, doc: "Type of Moving Average"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "aroon",
        doc: "Aroon",
        target: "TA_AROON",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [
          %{name: :aroon_down, type: :double_array},
          %{name: :aroon_up, type: :double_array}
        ]
      },
      %{
        name: "aroonosc",
        doc: "Aroon Oscillator",
        target: "TA_AROONOSC",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "asin",
        doc: "Vector Trigonometric ASin",
        target: "TA_ASIN",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "atan",
        doc: "Vector Trigonometric ATan",
        target: "TA_ATAN",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "atr",
        doc: "Average True Range",
        target: "TA_ATR",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "avgprice",
        doc: "Average Price",
        target: "TA_AVGPRICE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "avgdev",
        doc: "Average Deviation",
        target: "TA_AVGDEV",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "bbands",
        doc: "Bollinger Bands",
        target: "TA_BBANDS",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 5,
            doc: "Number of period"
          },
          %{
            name: :nb_dev_up,
            type: :double,
            min: -30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 2.0,
            doc: "Deviation multiplier for upper band"
          },
          %{
            name: :nb_dev_dn,
            type: :double,
            min: -30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 2.0,
            doc: "Deviation multiplier for lower band"
          },
          %{name: :ma_type, type: :ma_type, default: :sma, doc: "Type of Moving Average"}
        ],
        outputs: [
          %{name: :real_upper_band, type: :double_array},
          %{name: :real_middle_band, type: :double_array},
          %{name: :real_lower_band, type: :double_array}
        ]
      },
      %{
        name: "beta",
        doc: "Beta",
        target: "TA_BETA",
        inputs: [
          %{name: :values0, type: :double_array},
          %{name: :values1, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 5,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "bop",
        doc: "Balance Of Power",
        target: "TA_BOP",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "cci",
        doc: "Commodity Channel Index",
        target: "TA_CCI",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "cdl2crows",
        doc: "Two Crows",
        target: "TA_CDL2CROWS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3blackcrows",
        doc: "Three Black Crows",
        target: "TA_CDL3BLACKCROWS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3inside",
        doc: "Three Inside Up/Down",
        target: "TA_CDL3INSIDE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3linestrike",
        doc: "Three-Line Strike ",
        target: "TA_CDL3LINESTRIKE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3outside",
        doc: "Three Outside Up/Down",
        target: "TA_CDL3OUTSIDE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3starsinsouth",
        doc: "Three Stars In The South",
        target: "TA_CDL3STARSINSOUTH",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdl3whitesoldiers",
        doc: "Three Advancing White Soldiers",
        target: "TA_CDL3WHITESOLDIERS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlabandonedbaby",
        doc: "Abandoned Baby",
        target: "TA_CDLABANDONEDBABY",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.3,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdladvanceblock",
        doc: "Advance Block",
        target: "TA_CDLADVANCEBLOCK",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlbelthold",
        doc: "Belt-hold",
        target: "TA_CDLBELTHOLD",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlbreakaway",
        doc: "Breakaway",
        target: "TA_CDLBREAKAWAY",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlclosingmarubozu",
        doc: "Closing Marubozu",
        target: "TA_CDLCLOSINGMARUBOZU",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlconcealbabyswall",
        doc: "Concealing Baby Swallow",
        target: "TA_CDLCONCEALBABYSWALL",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlcounterattack",
        doc: "Counterattack",
        target: "TA_CDLCOUNTERATTACK",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdldarkcloudcover",
        doc: "Dark Cloud Cover",
        target: "TA_CDLDARKCLOUDCOVER",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.5,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdldoji",
        doc: "Doji",
        target: "TA_CDLDOJI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdldojistar",
        doc: "Doji Star",
        target: "TA_CDLDOJISTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdldragonflydoji",
        doc: "Dragonfly Doji",
        target: "TA_CDLDRAGONFLYDOJI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlengulfing",
        doc: "Engulfing Pattern",
        target: "TA_CDLENGULFING",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdleveningdojistar",
        doc: "Evening Doji Star",
        target: "TA_CDLEVENINGDOJISTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.3,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdleveningstar",
        doc: "Evening Star",
        target: "TA_CDLEVENINGSTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.3,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlgapsidesidewhite",
        doc: "Up/Down-gap side-by-side white lines",
        target: "TA_CDLGAPSIDESIDEWHITE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlgravestonedoji",
        doc: "Gravestone Doji",
        target: "TA_CDLGRAVESTONEDOJI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhammer",
        doc: "Hammer",
        target: "TA_CDLHAMMER",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhangingman",
        doc: "Hanging Man",
        target: "TA_CDLHANGINGMAN",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlharami",
        doc: "Harami Pattern",
        target: "TA_CDLHARAMI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlharamicross",
        doc: "Harami Cross Pattern",
        target: "TA_CDLHARAMICROSS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhighwave",
        doc: "High-Wave Candle",
        target: "TA_CDLHIGHWAVE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhikkake",
        doc: "Hikkake Pattern",
        target: "TA_CDLHIKKAKE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhikkakemod",
        doc: "Modified Hikkake Pattern",
        target: "TA_CDLHIKKAKEMOD",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlhomingpigeon",
        doc: "Homing Pigeon",
        target: "TA_CDLHOMINGPIGEON",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlidentical3crows",
        doc: "Identical Three Crows",
        target: "TA_CDLIDENTICAL3CROWS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlinneck",
        doc: "In-Neck Pattern",
        target: "TA_CDLINNECK",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlinvertedhammer",
        doc: "Inverted Hammer",
        target: "TA_CDLINVERTEDHAMMER",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlkicking",
        doc: "Kicking",
        target: "TA_CDLKICKING",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlkickingbylength",
        doc: "Kicking - bull/bear determined by the longer marubozu",
        target: "TA_CDLKICKINGBYLENGTH",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlladderbottom",
        doc: "Ladder Bottom",
        target: "TA_CDLLADDERBOTTOM",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdllongleggeddoji",
        doc: "Long Legged Doji",
        target: "TA_CDLLONGLEGGEDDOJI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdllongline",
        doc: "Long Line Candle",
        target: "TA_CDLLONGLINE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlmarubozu",
        doc: "Marubozu",
        target: "TA_CDLMARUBOZU",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlmatchinglow",
        doc: "Matching Low",
        target: "TA_CDLMATCHINGLOW",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlmathold",
        doc: "Mat Hold",
        target: "TA_CDLMATHOLD",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.5,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlmorningdojistar",
        doc: "Morning Doji Star",
        target: "TA_CDLMORNINGDOJISTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.3,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlmorningstar",
        doc: "Morning Star",
        target: "TA_CDLMORNINGSTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :penetration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.3,
            doc: "Percentage of penetration of a candle within another candle"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlonneck",
        doc: "On-Neck Pattern",
        target: "TA_CDLONNECK",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlpiercing",
        doc: "Piercing Pattern",
        target: "TA_CDLPIERCING",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlrickshawman",
        doc: "Rickshaw Man",
        target: "TA_CDLRICKSHAWMAN",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlrisefall3methods",
        doc: "Rising/Falling Three Methods",
        target: "TA_CDLRISEFALL3METHODS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlseparatinglines",
        doc: "Separating Lines",
        target: "TA_CDLSEPARATINGLINES",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlshootingstar",
        doc: "Shooting Star",
        target: "TA_CDLSHOOTINGSTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlshortline",
        doc: "Short Line Candle",
        target: "TA_CDLSHORTLINE",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlspinningtop",
        doc: "Spinning Top",
        target: "TA_CDLSPINNINGTOP",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlstalledpattern",
        doc: "Stalled Pattern",
        target: "TA_CDLSTALLEDPATTERN",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlsticksandwich",
        doc: "Stick Sandwich",
        target: "TA_CDLSTICKSANDWICH",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdltakuri",
        doc: "Takuri (Dragonfly Doji with very long lower shadow)",
        target: "TA_CDLTAKURI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdltasukigap",
        doc: "Tasuki Gap",
        target: "TA_CDLTASUKIGAP",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlthrusting",
        doc: "Thrusting Pattern",
        target: "TA_CDLTHRUSTING",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdltristar",
        doc: "Tristar Pattern",
        target: "TA_CDLTRISTAR",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlunique3river",
        doc: "Unique 3 River",
        target: "TA_CDLUNIQUE3RIVER",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlupsidegap2crows",
        doc: "Upside Gap Two Crows",
        target: "TA_CDLUPSIDEGAP2CROWS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "cdlxsidegap3methods",
        doc: "Upside/Downside Gap Three Methods",
        target: "TA_CDLXSIDEGAP3METHODS",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "ceil",
        doc: "Vector Ceil",
        target: "TA_CEIL",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "cmo",
        doc: "Chande Momentum Oscillator",
        target: "TA_CMO",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "correl",
        doc: "Pearson's Correlation Coefficient (r)",
        target: "TA_CORREL",
        inputs: [
          %{name: :values0, type: :double_array},
          %{name: :values1, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "cos",
        doc: "Vector Trigonometric Cos",
        target: "TA_COS",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "cosh",
        doc: "Vector Trigonometric Cosh",
        target: "TA_COSH",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "dema",
        doc: "Double Exponential Moving Average",
        target: "TA_DEMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "div",
        doc: "Vector Arithmetic Div",
        target: "TA_DIV",
        inputs: [%{name: :values0, type: :double_array}, %{name: :values1, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "dx",
        doc: "Directional Movement Index",
        target: "TA_DX",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ema",
        doc: "Exponential Moving Average",
        target: "TA_EMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "exp",
        doc: "Vector Arithmetic Exp",
        target: "TA_EXP",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "floor",
        doc: "Vector Floor",
        target: "TA_FLOOR",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ht_dcperiod",
        doc: "Hilbert Transform - Dominant Cycle Period",
        target: "TA_HT_DCPERIOD",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ht_dcphase",
        doc: "Hilbert Transform - Dominant Cycle Phase",
        target: "TA_HT_DCPHASE",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ht_phasor",
        doc: "Hilbert Transform - Phasor Components",
        target: "TA_HT_PHASOR",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [
          %{name: :in_phase, type: :double_array},
          %{name: :quadrature, type: :double_array}
        ]
      },
      %{
        name: "ht_sine",
        doc: "Hilbert Transform - SineWave",
        target: "TA_HT_SINE",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :sine, type: :double_array}, %{name: :lead_sine, type: :double_array}]
      },
      %{
        name: "ht_trendline",
        doc: "Hilbert Transform - Instantaneous Trendline",
        target: "TA_HT_TRENDLINE",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ht_trendmode",
        doc: "Hilbert Transform - Trend vs Cycle Mode",
        target: "TA_HT_TRENDMODE",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "imi",
        doc: "Intraday Momentum Index",
        target: "TA_IMI",
        inputs: [
          %{name: :open, type: :double_array, doc: "Open Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "kama",
        doc: "Kaufman Adaptive Moving Average",
        target: "TA_KAMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "linearreg",
        doc: "Linear Regression",
        target: "TA_LINEARREG",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "linearreg_angle",
        doc: "Linear Regression Angle",
        target: "TA_LINEARREG_ANGLE",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "linearreg_intercept",
        doc: "Linear Regression Intercept",
        target: "TA_LINEARREG_INTERCEPT",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "linearreg_slope",
        doc: "Linear Regression Slope",
        target: "TA_LINEARREG_SLOPE",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ln",
        doc: "Vector Log Natural",
        target: "TA_LN",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "log10",
        doc: "Vector Log10",
        target: "TA_LOG10",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ma",
        doc: "Moving average",
        target: "TA_MA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          },
          %{name: :ma_type, type: :ma_type, default: :sma, doc: "Type of Moving Average"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "macd",
        doc: "Moving Average Convergence/Divergence",
        target: "TA_MACD",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :fast_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 12,
            doc: "Number of period for the fast MA"
          },
          %{
            name: :slow_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 26,
            doc: "Number of period for the slow MA"
          },
          %{
            name: :signal_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 9,
            doc: "Smoothing for the signal line (nb of period)"
          }
        ],
        outputs: [
          %{name: :macd, type: :double_array},
          %{name: :macd_signal, type: :double_array},
          %{name: :macd_hist, type: :double_array}
        ]
      },
      %{
        name: "macdext",
        doc: "MACD with controllable MA type",
        target: "TA_MACDEXT",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :fast_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 12,
            doc: "Number of period for the fast MA"
          },
          %{
            name: :fast_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for fast MA"
          },
          %{
            name: :slow_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 26,
            doc: "Number of period for the slow MA"
          },
          %{
            name: :slow_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for slow MA"
          },
          %{
            name: :signal_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 9,
            doc: "Smoothing for the signal line (nb of period)"
          },
          %{
            name: :signal_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for signal line"
          }
        ],
        outputs: [
          %{name: :macd, type: :double_array},
          %{name: :macd_signal, type: :double_array},
          %{name: :macd_hist, type: :double_array}
        ]
      },
      %{
        name: "macdfix",
        doc: "Moving Average Convergence/Divergence Fix 12/26",
        target: "TA_MACDFIX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :signal_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 9,
            doc: "Smoothing for the signal line (nb of period)"
          }
        ],
        outputs: [
          %{name: :macd, type: :double_array},
          %{name: :macd_signal, type: :double_array},
          %{name: :macd_hist, type: :double_array}
        ]
      },
      %{
        name: "mama",
        doc: "MESA Adaptive Moving Average",
        target: "TA_MAMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :fast_limit,
            type: :double,
            min: 0.01,
            max: 0.99,
            default: 0.5,
            doc: "Upper limit use in the adaptive algorithm"
          },
          %{
            name: :slow_limit,
            type: :double,
            min: 0.01,
            max: 0.99,
            default: 0.05,
            doc: "Lower limit use in the adaptive algorithm"
          }
        ],
        outputs: [%{name: :mama, type: :double_array}, %{name: :fama, type: :double_array}]
      },
      %{
        name: "mavp",
        doc: "Moving average with variable period",
        target: "TA_MAVP",
        inputs: [
          %{name: :values, type: :double_array},
          %{name: :periods, type: :double_array},
          %{
            name: :min_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 2,
            doc: "Value less than minimum will be changed to Minimum period"
          },
          %{
            name: :max_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Value higher than maximum will be changed to Maximum period"
          },
          %{name: :ma_type, type: :ma_type, default: :sma, doc: "Type of Moving Average"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "max",
        doc: "Highest value over a specified period",
        target: "TA_MAX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "maxindex",
        doc: "Index of highest value over a specified period",
        target: "TA_MAXINDEX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "medprice",
        doc: "Median Price",
        target: "TA_MEDPRICE",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "mfi",
        doc: "Money Flow Index",
        target: "TA_MFI",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{name: :volume, type: :double_array, doc: "Volume List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "midpoint",
        doc: "MidPoint over period",
        target: "TA_MIDPOINT",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "midprice",
        doc: "Midpoint Price over period",
        target: "TA_MIDPRICE",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "min",
        doc: "Lowest value over a specified period",
        target: "TA_MIN",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "minindex",
        doc: "Index of lowest value over a specified period",
        target: "TA_MININDEX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :integer_array}]
      },
      %{
        name: "minmax",
        doc: "Lowest and highest values over a specified period",
        target: "TA_MINMAX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :min, type: :double_array}, %{name: :max, type: :double_array}]
      },
      %{
        name: "minmaxindex",
        doc: "Indexes of lowest and highest values over a specified period",
        target: "TA_MINMAXINDEX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [
          %{name: :min_idx, type: :integer_array},
          %{name: :max_idx, type: :integer_array}
        ]
      },
      %{
        name: "minus_di",
        doc: "Minus Directional Indicator",
        target: "TA_MINUS_DI",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "minus_dm",
        doc: "Minus Directional Movement",
        target: "TA_MINUS_DM",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "mom",
        doc: "Momentum",
        target: "TA_MOM",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 10,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "mult",
        doc: "Vector Arithmetic Mult",
        target: "TA_MULT",
        inputs: [%{name: :values0, type: :double_array}, %{name: :values1, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "natr",
        doc: "Normalized Average True Range",
        target: "TA_NATR",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "obv",
        doc: "On Balance Volume",
        target: "TA_OBV",
        inputs: [
          %{name: :values, type: :double_array},
          %{name: :volume, type: :double_array, doc: "Volume List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "plus_di",
        doc: "Plus Directional Indicator",
        target: "TA_PLUS_DI",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "plus_dm",
        doc: "Plus Directional Movement",
        target: "TA_PLUS_DM",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ppo",
        doc: "Percentage Price Oscillator",
        target: "TA_PPO",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :fast_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 12,
            doc: "Number of period for the fast MA"
          },
          %{
            name: :slow_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 26,
            doc: "Number of period for the slow MA"
          },
          %{name: :ma_type, type: :ma_type, default: :sma, doc: "Type of Moving Average"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "roc",
        doc: "Rate of change : ((price/prevPrice)-1)*100",
        target: "TA_ROC",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 10,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "rocp",
        doc: "Rate of change Percentage: (price-prevPrice)/prevPrice",
        target: "TA_ROCP",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 10,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "rocr",
        doc: "Rate of change ratio: (price/prevPrice)",
        target: "TA_ROCR",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 10,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "rocr100",
        doc: "Rate of change ratio 100 scale: (price/prevPrice)*100",
        target: "TA_ROCR100",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 10,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "rsi",
        doc: "Relative Strength Index",
        target: "TA_RSI",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sar",
        doc: "Parabolic SAR",
        target: "TA_SAR",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :acceleration,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.02,
            doc: "Acceleration Factor used up to the Maximum value"
          },
          %{
            name: :maximum,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.2,
            doc: "Acceleration Factor Maximum value"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sarext",
        doc: "Parabolic SAR - Extended",
        target: "TA_SAREXT",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{
            name: :start_value,
            type: :double,
            min: -30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.0,
            doc: "Start value and direction. 0 for Auto, >0 for Long, <0 for Short"
          },
          %{
            name: :offset_on_reverse,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.0,
            doc: "Percent offset added/removed to initial stop on short/long reversal"
          },
          %{
            name: :acceleration_init_long,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.02,
            doc: "Acceleration Factor initial value for the Long direction"
          },
          %{
            name: :acceleration_long,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.02,
            doc: "Acceleration Factor for the Long direction"
          },
          %{
            name: :acceleration_max_long,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.2,
            doc: "Acceleration Factor maximum value for the Long direction"
          },
          %{
            name: :acceleration_init_short,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.02,
            doc: "Acceleration Factor initial value for the Short direction"
          },
          %{
            name: :acceleration_short,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.02,
            doc: "Acceleration Factor for the Short direction"
          },
          %{
            name: :acceleration_max_short,
            type: :double,
            min: 0.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 0.2,
            doc: "Acceleration Factor maximum value for the Short direction"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sin",
        doc: "Vector Trigonometric Sin",
        target: "TA_SIN",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sinh",
        doc: "Vector Trigonometric Sinh",
        target: "TA_SINH",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sma",
        doc: "Simple Moving Average",
        target: "TA_SMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sqrt",
        doc: "Vector Square Root",
        target: "TA_SQRT",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "stddev",
        doc: "Standard Deviation",
        target: "TA_STDDEV",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 5,
            doc: "Number of period"
          },
          %{
            name: :nb_dev,
            type: :double,
            min: -30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 1.0,
            doc: "Nb of deviations"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "stoch",
        doc: "Stochastic",
        target: "TA_STOCH",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :fast_k_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 5,
            doc: "Time period for building the Fast-K line"
          },
          %{
            name: :slow_k_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 3,
            doc: "Smoothing for making the Slow-K line. Usually set to 3"
          },
          %{
            name: :slow_k_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for Slow-K"
          },
          %{
            name: :slow_d_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 3,
            doc: "Smoothing for making the Slow-D line"
          },
          %{
            name: :slow_d_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for Slow-D"
          }
        ],
        outputs: [%{name: :slow_k, type: :double_array}, %{name: :slow_d, type: :double_array}]
      },
      %{
        name: "stochf",
        doc: "Stochastic Fast",
        target: "TA_STOCHF",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :fast_k_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 5,
            doc: "Time period for building the Fast-K line"
          },
          %{
            name: :fast_d_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 3,
            doc: "Smoothing for making the Fast-D line. Usually set to 3"
          },
          %{
            name: :fast_d_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for Fast-D"
          }
        ],
        outputs: [%{name: :fast_k, type: :double_array}, %{name: :fast_d, type: :double_array}]
      },
      %{
        name: "stochrsi",
        doc: "Stochastic Relative Strength Index",
        target: "TA_STOCHRSI",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          },
          %{
            name: :fast_k_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 5,
            doc: "Time period for building the Fast-K line"
          },
          %{
            name: :fast_d_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 3,
            doc: "Smoothing for making the Fast-D line. Usually set to 3"
          },
          %{
            name: :fast_d_ma_type,
            type: :ma_type,
            default: :sma,
            doc: "Type of Moving Average for Fast-D"
          }
        ],
        outputs: [%{name: :fast_k, type: :double_array}, %{name: :fast_d, type: :double_array}]
      },
      %{
        name: "sub",
        doc: "Vector Arithmetic Subtraction",
        target: "TA_SUB",
        inputs: [%{name: :values0, type: :double_array}, %{name: :values1, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "sum",
        doc: "Summation",
        target: "TA_SUM",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "t3",
        doc: "Triple Exponential Moving Average (T3)",
        target: "TA_T3",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 5,
            doc: "Number of period"
          },
          %{
            name: :v_factor,
            type: :double,
            min: 0.0,
            max: 1.0,
            default: 0.7,
            doc: "Volume Factor"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "tan",
        doc: "Vector Trigonometric Tan",
        target: "TA_TAN",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "tanh",
        doc: "Vector Trigonometric Tanh",
        target: "TA_TANH",
        inputs: [%{name: :values, type: :double_array}],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "tema",
        doc: "Triple Exponential Moving Average",
        target: "TA_TEMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "trange",
        doc: "True Range",
        target: "TA_TRANGE",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "trima",
        doc: "Triangular Moving Average",
        target: "TA_TRIMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "trix",
        doc: "1-day Rate-Of-Change (ROC) of a Triple Smooth EMA",
        target: "TA_TRIX",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "tsf",
        doc: "Time Series Forecast",
        target: "TA_TSF",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "typprice",
        doc: "Typical Price",
        target: "TA_TYPPRICE",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "ultosc",
        doc: "Ultimate Oscillator",
        target: "TA_ULTOSC",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period1,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 7,
            doc: "Number of bars for 1st period."
          },
          %{
            name: :time_period2,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 14,
            doc: "Number of bars fro 2nd period"
          },
          %{
            name: :time_period3,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 28,
            doc: "Number of bars for 3rd period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "var",
        doc: "Variance",
        target: "TA_VAR",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 1,
            max: 100_000,
            default: 5,
            doc: "Number of period"
          },
          %{
            name: :nb_dev,
            type: :double,
            min: -30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            max: 30_000_000_000_000_002_158_062_836_758_597_337_088.0,
            default: 1.0,
            doc: "Nb of deviations"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "wclprice",
        doc: "Weighted Close Price",
        target: "TA_WCLPRICE",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"}
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "willr",
        doc: "Williams' %R",
        target: "TA_WILLR",
        inputs: [
          %{name: :high, type: :double_array, doc: "High Price List"},
          %{name: :low, type: :double_array, doc: "Low Price List"},
          %{name: :close, type: :double_array, doc: "Close Price List"},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 14,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      },
      %{
        name: "wma",
        doc: "Weighted Moving Average",
        target: "TA_WMA",
        inputs: [
          %{name: :values, type: :double_array},
          %{
            name: :time_period,
            type: :integer,
            min: 2,
            max: 100_000,
            default: 30,
            doc: "Number of period"
          }
        ],
        outputs: [%{name: :result, type: :double_array}]
      }
    ]
  end
end
