#!/usr/bin/env elixir
#
# Reads tools/talib_functions.json (produced by talib_introspect)
# and generates lib/mix/tasks/function_def.ex
#
# Usage:
#   elixir tools/generate_function_def.exs
#

defmodule Generator do
  @json_path Path.join([__DIR__, "talib_functions.json"])
  @output_path Path.join([__DIR__, "..", "lib", "mix", "tasks", "function_def.ex"])

  def run do
    functions = @json_path |> File.read!() |> Jason.decode!()

    entries =
      functions
      |> Enum.map(&build_entry/1)
      |> Enum.join(",\n")

    content = """
    defmodule TalibEx.FunctionDef do
      @moduledoc false
      # Generated by tools/generate_function_def.exs — do not edit manually.

      def mapping do
        [
    #{entries}
        ]
      end
    end
    """

    formatted = Code.format_string!(content) |> to_string()
    File.write!(@output_path, formatted <> "\n")
    IO.puts("Generated #{@output_path}")
    IO.puts("Total functions: #{length(functions)}")
  end

  defp build_entry(func) do
    name = ta_name_to_snake(func["name"], func["camel_case_name"])
    target = "TA_#{func["name"]}"
    doc = func["hint"]
    inputs = build_inputs(func["inputs"], func["opt_inputs"])
    outputs = build_outputs(func["outputs"])

    "%{name: #{inspect(name)}, doc: #{inspect(doc)}, target: #{inspect(target)}, inputs: [#{Enum.join(inputs, ", ")}], outputs: [#{Enum.join(outputs, ", ")}]}"
  end

  defp build_inputs(inputs, opt_inputs) do
    regular = Enum.flat_map(inputs, &expand_input/1)
    optional = Enum.map(opt_inputs, &build_opt_input/1)
    regular ++ optional
  end

  defp expand_input(%{"type" => "price", "price_components" => components}) do
    # Expand price input into individual OHLCV arrays based on flags
    order = [
      {"open", "open", "Open Price List"},
      {"high", "high", "High Price List"},
      {"low", "low", "Low Price List"},
      {"close", "close", "Close Price List"},
      {"volume", "volume", "Volume List"},
      {"open_interest", "open_interest", "Open Interest List"}
    ]

    for {key, name, doc} <- order, components[key] == true do
      "%{name: :#{name}, type: :double_array, doc: #{inspect(doc)}}"
    end
  end

  defp expand_input(%{"type" => "real", "param_name" => param_name}) do
    name = param_name_to_atom(param_name)
    ["%{name: :#{name}, type: :double_array}"]
  end

  defp expand_input(%{"type" => "integer", "param_name" => param_name}) do
    name = param_name_to_atom(param_name)
    ["%{name: :#{name}, type: :double_array}"]
  end

  defp build_opt_input(%{"type" => "integer_range"} = opt) do
    name = param_name_to_atom(opt["param_name"])
    default = trunc(opt["default_value"])
    hint = opt["hint"] || opt["display_name"]

    range = opt["range"]
    min_val = if range, do: range["min"], else: nil
    max_val = if range, do: range["max"], else: nil

    fields = [
      "name: :#{name}",
      "type: :integer",
      if(min_val, do: "min: #{min_val}"),
      if(max_val, do: "max: #{max_val}"),
      "default: #{default}",
      if(hint, do: "doc: #{inspect(hint)}")
    ]

    "%{#{fields |> Enum.reject(&is_nil/1) |> Enum.join(", ")}}"
  end

  defp build_opt_input(%{"type" => "real_range"} = opt) do
    name = param_name_to_atom(opt["param_name"])
    default = opt["default_value"]
    hint = opt["hint"] || opt["display_name"]

    range = opt["range"]
    min_val = if range, do: range["min"], else: nil
    max_val = if range, do: range["max"], else: nil

    fields = [
      "name: :#{name}",
      "type: :double",
      if(min_val, do: "min: #{format_float(min_val)}"),
      if(max_val && max_val < 1.0e300, do: "max: #{format_float(max_val)}"),
      "default: #{format_float(default)}",
      if(hint, do: "doc: #{inspect(hint)}")
    ]

    "%{#{fields |> Enum.reject(&is_nil/1) |> Enum.join(", ")}}"
  end

  defp build_opt_input(%{"type" => "integer_list"} = opt) do
    # MA type or similar enum list
    name = param_name_to_atom(opt["param_name"])
    default_val = trunc(opt["default_value"])
    hint = opt["hint"] || opt["display_name"]

    # Check if this is a MA type list
    values = opt["values"] || []
    is_ma_type = Enum.any?(values, fn v -> v["string"] == "SMA" || v["string"] == "Sma" end)

    if is_ma_type do
      default_atom = ma_type_default(default_val)
      fields = [
        "name: :#{name}",
        "type: :ma_type",
        "default: #{inspect(default_atom)}",
        if(hint, do: "doc: #{inspect(hint)}")
      ]

      "%{#{fields |> Enum.reject(&is_nil/1) |> Enum.join(", ")}}"
    else
      fields = [
        "name: :#{name}",
        "type: :integer",
        "default: #{default_val}",
        if(hint, do: "doc: #{inspect(hint)}")
      ]

      "%{#{fields |> Enum.reject(&is_nil/1) |> Enum.join(", ")}}"
    end
  end

  defp build_opt_input(%{"type" => "real_list"} = opt) do
    name = param_name_to_atom(opt["param_name"])
    default = opt["default_value"]
    hint = opt["hint"] || opt["display_name"]

    fields = [
      "name: :#{name}",
      "type: :double",
      "default: #{format_float(default)}",
      if(hint, do: "doc: #{inspect(hint)}")
    ]

    "%{#{fields |> Enum.reject(&is_nil/1) |> Enum.join(", ")}}"
  end

  defp build_outputs(outputs) do
    case outputs do
      [single] ->
        [build_output(single, true)]

      multiple ->
        Enum.map(multiple, &build_output(&1, false))
    end
  end

  defp build_output(%{"type" => type, "param_name" => param_name}, single?) do
    elixir_type = if type == "integer", do: ":integer_array", else: ":double_array"

    name =
      if single? do
        ":result"
      else
        name = param_name_to_atom(param_name)
        ":#{name}"
      end

    "%{name: #{name}, type: #{elixir_type}}"
  end

  # Convert "optInTimePeriod" -> "time_period", "inReal" -> "values", etc.
  defp param_name_to_atom("inReal"), do: "values"
  defp param_name_to_atom("inReal0"), do: "values0"
  defp param_name_to_atom("inReal1"), do: "values1"
  defp param_name_to_atom("inPeriods"), do: "periods"
  defp param_name_to_atom("inInteger"), do: "values"
  defp param_name_to_atom("inInteger0"), do: "values0"
  defp param_name_to_atom("inInteger1"), do: "values1"
  defp param_name_to_atom("inPriceOHLCV"), do: "price"
  defp param_name_to_atom("inPriceHLC"), do: "price"
  defp param_name_to_atom("inPriceHL"), do: "price"
  defp param_name_to_atom("inPriceOHLC"), do: "price"

  defp param_name_to_atom("optIn" <> rest), do: to_snake_case(rest)
  defp param_name_to_atom("out" <> rest), do: to_snake_case(rest)
  defp param_name_to_atom(name), do: to_snake_case(name)

  defp ma_type_default(0), do: :sma
  defp ma_type_default(1), do: :ema
  defp ma_type_default(2), do: :wma
  defp ma_type_default(3), do: :dema
  defp ma_type_default(4), do: :tema
  defp ma_type_default(5), do: :trima
  defp ma_type_default(6), do: :kama
  defp ma_type_default(7), do: :mama
  defp ma_type_default(8), do: :t3
  defp ma_type_default(_), do: :sma

  defp ta_name_to_snake(name, _camel) do
    String.downcase(name)
  end

  defp to_snake_case(str) do
    str
    |> String.replace(~r/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    |> String.replace(~r/([a-z0-9])([A-Z])/, "\\1_\\2")
    |> String.downcase()
  end

  defp format_float(val) when is_float(val) do
    if val == Float.round(val) do
      "#{trunc(val)}.0"
    else
      "#{val}"
    end
  end

  defp format_float(val) when is_integer(val), do: "#{val}.0"
end

# Ensure Jason is available
Mix.install([{:jason, "~> 1.4"}])
Generator.run()
